### ISSUE TITLE
Naver Map 기능 구현

### ISSUE THREAD

**Issue by hakzzang** [boostcampth/boostcamp3_C#63]

**Comment by leeyc09** [comment]
네이버 지도 api 사용건에 대하여
https://www.ncloud.com/product/applicationService/maps
모바일 Mobile Dynamic Map 서비스만 무료이고 지오코딩 및 길찾기 등등 api 사용은 건당 비용이 발생합니다.
비용관련 문제는 해결 된 건가요?

**Comment by hakzzang** [comment]
> 네이버 지도 api 사용건에 대하여
> https://www.ncloud.com/product/applicationService/maps
> 모바일 Mobile Dynamic Map 서비스만 무료이고 지오코딩 및 길찾기 등등 api 사용은 건당 비용이 발생합니다.
> 비용관련 문제는 해결 된 건가요?

![image](https://user-images.githubusercontent.com/22374750/52174346-9acaa580-27d5-11e9-98f1-95da0edd9a3b.png)

네이버에서 1년동안 프로모션으로 많은 수의 트랜잭션이 일어나더라도 대부분은 무료로 되고
있는 것 같습니다. 또한 비용 관련해서는 이렇게 교묘하게 피해가고 있습니다.

**Comment by leeyc09** [comment]
과연 그렇군요!

**Comment by leeyc09** [comment]
...ncloud 지도 api  sdk 28에서 NMapActivity 확장해서 만들면 fragment 관련 문제가 있네요

아..어찌어찌 구현은 가능하군요...
