### ISSUE TITLE
dev repository에서 발견된 버그 입니다.

### ISSUE THREAD

**Issue by leeyc09** [boostcampth/boostcamp3_C#65]
1. 메인화면 하단 bottom sheet
하단에 개발된 바텀시트를 아래로 스크롤해서 내리면 화면밖으로 사라져 다시 올라오지 않는 문제가 있습니다.

2.   build 문제
annotationProcessor -> kapt로 변경해야 빌드 시 오류가 발생하지 않습니다.

**Comment by hakzzang** [comment]
> 1. 메인화면 하단 bottom sheet
>    하단에 개발된 바텀시트를 아래로 스크롤해서 내리면 화면밖으로 사라져 다시 올라오지 않는 문제가 있습니다.
> 2. build 문제
>    annotationProcessor -> kapt로 변경해야 빌드 시 오류가 발생하지 않습니다.

빠르게 해결하도록 하겠습니다!

**Comment by weedrice** [comment]
확인했습니다!!

**Comment by hakzzang** [comment]
> 1. 메인화면 하단 bottom sheet
>    하단에 개발된 바텀시트를 아래로 스크롤해서 내리면 화면밖으로 사라져 다시 올라오지 않는 문제가 있습니다.
> 2. build 문제
>    annotationProcessor -> kapt로 변경해야 빌드 시 오류가 발생하지 않습니다.

2. build 문제 관련
3c46e793561a79e280a8c175c50e2c308160164e 대응했습니다.

**Comment by weedrice** [comment]
1. bottom sheet
사라지는 현상 issue 56에서 수정했습니다.
